# Конфигурация Video Uploader App
# ================================

# Основные настройки
videos_dir: "./VideosDirPath"          # Папка с видео для загрузки
uploaded_dir: "./uploaded"             # Папка для загруженных видео
titles_file: "./titles.txt"            # Файл с заголовками

# Логирование
log_level: "INFO"                      # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file: "./logs/uploader.log"        # Путь к файлу логов

# Telegram уведомления
telegram_enabled: true                 # Включить уведомления в Telegram
telegram_token: ""                     # Токен бота (или через переменную TELEGRAM_BOT_TOKEN)
telegram_chat_id: ""                   # ID чата (или через переменную TELEGRAM_CHAT_ID)

# Планировщик задач
scheduler_enabled: true                # Включить планировщик
max_concurrent_uploads: 2              # Максимум одновременных загрузок

# GUI веб-интерфейс  
gui_enabled: true                      # Включить веб-интерфейс
gui_host: "127.0.0.1"                  # Хост для веб-интерфейса
gui_port: 8080                         # Порт для веб-интерфейса

# Настройки TikTok
tiktok:
  enabled: true                        # Включить TikTok загрузки
  cookies_path: "./CookiesDir/tiktok_session-toptrailer82.cookie"
  proxy: ""                            # host:port или через переменную PROXY
  proxy_user: ""                       # или через переменную PROXY_USER
  proxy_pass: ""                       # или через переменную PROXY_PASS
  retry_attempts: 3                    # Количество попыток при ошибке
  upload_delay: 5                      # Задержка между загрузками (секунды)
  rate_limit: 10                       # Максимум загрузок в час

# Настройки Instagram (пока не реализовано)
instagram:
  enabled: false                       # Включить Instagram загрузки
  cookies_path: "./CookiesDir/instagram_session.cookie"
  proxy: ""
  proxy_user: ""
  proxy_pass: ""
  retry_attempts: 3
  upload_delay: 10
  rate_limit: 5

# Дополнительные настройки
# ========================

# Мониторинг файлов
file_monitoring:
  watch_directory: true                # Следить за новыми файлами
  auto_upload: false                   # Автоматически загружать новые файлы
  supported_formats: [".mp4", ".mov", ".avi", ".webm"]

# Обработка видео
video_processing:
  validate_before_upload: true         # Проверять видео перед загрузкой
  create_thumbnails: false             # Создавать превью (требует ffmpeg)
  compress_if_needed: false            # Сжимать большие файлы

# Резервное копирование
backup:
  enabled: false                       # Создавать бэкапы перед загрузкой
  backup_dir: "./backup"
  keep_days: 7                         # Хранить бэкапы N дней

# Уведомления
notifications:
  on_success: true                     # Уведомлять об успешных загрузках
  on_failure: true                     # Уведомлять об ошибках
  on_schedule_complete: true           # Уведомлять о завершении расписания
  
# Безопасность
security:
  encrypt_cookies: false               # Шифровать файлы cookies
  secure_logs: true                    # Не логировать чувствительную информацию
  max_file_size_mb: 4096              # Максимальный размер файла